In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
plt.style.use("default")

In [2]:
pd.options.display.max_rows = 4

In [3]:
# Add the python path to the folder containing some custom packages.
import sys
sys.path.insert(0, "../packages/")
from TsIP.TsIP import TsIP

In [4]:
# Set default sizes for figures.
plt.style.use("default") # style matplotlib
plt.rc("axes", labelsize = 15) # fontsize of the x and y labels
plt.rc("axes", titlesize = 15) # fontsize of the axes title
plt.rc("xtick", labelsize = 15) # fontsize of the tick labels
plt.rc("ytick", labelsize = 15) # fontsize of the tick labels
plt.rc("legend", fontsize = 15) # legend fontsize

# Nigeria

I create the dataset of multivariate time-series.

In [5]:
COUNTRY = "Nigeria"
PATH_TO_SAVE = "./output_data/Nigeria/"
PATH_TO_DATA_FOLDER = "../Data Sources/"

## Data sources

For more details regarding each single data source see the folder *Data Sources*.

In [6]:
# Load the data of the fcs indicator released by wfp.
fcs = pd.read_csv(PATH_TO_DATA_FOLDER + f"1. Food Consumption Score (FCS)/output_timeseries/{COUNTRY}/wfp_fcs-interpolate.csv", header = [0, 1], index_col = 0)
fcs.index.name = "Datetime"
fcs.index = pd.to_datetime(fcs.index)
freq = "D"
fcs.index.freq = freq

# Load the the data of the rcsi indicator released by wfp.
rcsi = pd.read_csv(PATH_TO_DATA_FOLDER + f"2. Reduced Coping Strategy Index (rCSI)/output_timeseries/{COUNTRY}/wfp_rcsi-interpolate.csv", header = [0, 1], index_col = 0)
rcsi.index.name = "Datetime"
rcsi.index = pd.to_datetime(rcsi.index)
freq = "D"
rcsi.index.freq = freq

# Load the data of market prices indicator released by wfp.
price = pd.read_csv(PATH_TO_DATA_FOLDER + f"3. Market Prices/output_timeseries/{COUNTRY}/wfp_market_price-interpolate.csv", header = [0, 1], index_col = 0)
price.index.name = "Datetime"
price.index = pd.to_datetime(price.index)
freq = "D"
price.index.freq = freq

# Load the data of rainfall indicator released by wfp.
rainfall = pd.read_csv(PATH_TO_DATA_FOLDER + f"4. Rainfall & Vegetation/output_timeseries/{COUNTRY}/wfp_rainfall.csv", header = [0, 1], index_col = 0)
rainfall.index.name = "Datetime"
rainfall.index = pd.to_datetime(rainfall.index)
freq = "D"
rainfall.index.freq = freq

# Load the data of vegetation indicator released by wfp.
NDVI = pd.read_csv(PATH_TO_DATA_FOLDER + f"4. Rainfall & Vegetation/output_timeseries/{COUNTRY}/wfp_NDVI.csv", header = [0, 1], index_col = 0)
NDVI.index.name = "Datetime"
NDVI.index = pd.to_datetime(NDVI.index)
freq = "D"
NDVI.index.freq = freq

# Load the data of conflicts indicator released by ACLED.
conflict = pd.read_csv(PATH_TO_DATA_FOLDER + f"5. Conflicts/output_timeseries/{COUNTRY}/wfp_conflicts-SvyWindow.csv", header = [0, 1], index_col = 0)
conflict.index.name = "Datetime"
conflict.index = pd.to_datetime(conflict.index)
freq = "D"
conflict.index.freq = freq

# Load the data of administrative codes.
admin_code = pd.read_csv(PATH_TO_DATA_FOLDER + f"6. Adminstrata Code/output_timeseries/{COUNTRY}/wfp_adminstrata_code.csv", header = [0, 1], index_col = 0)
admin_code.index.name = "Datetime"
admin_code.index = pd.to_datetime(admin_code.index)
freq = "D"
admin_code.index.freq = freq

# Load the data of Ramadan.
ramadan = pd.read_csv(PATH_TO_DATA_FOLDER + f"7. Ramadan/output_timeseries/{COUNTRY}/wfp_ramadan_SvyWindow.csv", header = [0, 1], index_col = 0)
ramadan.index.name = "Datetime"
ramadan.index = pd.to_datetime(ramadan.index)
freq = "D"
ramadan.index.freq = freq

# Load the data of coordination.
coordinates = pd.read_csv(PATH_TO_DATA_FOLDER + f"8. Geospatial Data/output_timeseries/{COUNTRY}/wfp_geospatial.csv", header = [0, 1], index_col = 0)
coordinates.index.name = "Datetime"
coordinates.index = pd.to_datetime(coordinates.index)
freq = "D"
coordinates.index.freq = freq

# Load the data of population released by wfp.
population = pd.read_csv(PATH_TO_DATA_FOLDER + f"9. Population/output_timeseries/{COUNTRY}/wfp_population.csv", header = [0, 1], index_col = 0)
population.index.name = "Datetime"
population.index = pd.to_datetime(population.index)
freq = "D"
population.index.freq = freq

In [7]:
# Create the full dataset.
df = pd.concat([fcs, rcsi, rainfall, conflict, NDVI, admin_code, population, ramadan, price, coordinates], axis = 1, levels = 0).sort_index(axis = 1, level = [0, 1])
df.head()

AdminStrata      Abia                                    \
Indicator        Area Code       Lat      Lon Waterways
Datetime
2018-01-01   0.396543   40  5.453302  7.52319  0.897617
2018-01-02   0.396543   40  5.453302  7.52319  0.897617
...               ...  ...       ...      ...       ...
2018-01-04   0.396543   40  5.453302  7.52319  0.897617
2018-01-05   0.396543   40  5.453302  7.52319  0.897617

AdminStrata                       Adamawa                                 \
Indicator   1 Month Anomaly Rainfalls (%) 3 Months Anomaly Rainfalls (%)
Datetime
2018-01-01                            NaN                            NaN
2018-01-02                            NaN                            NaN
...                                   ...                            ...
2018-01-04                            NaN                            NaN
2018-01-05                            NaN                            NaN

AdminStrata                     ...                     Yobe                 \
Indicator        Area Code FCG  ... Price cereals and tubers Rainfalls (mm)
Datetime                        ...
2018-01-01   3.113007   41 NaN  ...                      NaN            NaN
2018-01-02   3.113007   41 NaN  ...                      NaN            NaN
...               ...  ...  ..  ...                      ...            ...
2018-01-04   3.113007   41 NaN  ...                      NaN            NaN
2018-01-05   3.113007   41 NaN  ...                      NaN            NaN

AdminStrata                           Zamfara                            \
Indicator   Ramadan  Waterways rCSI      Area Code        Lat       Lon
Datetime
2018-01-01      NaN  11.177106  NaN  2.782855   76  12.101505  6.246535
2018-01-02      NaN  11.177106  NaN  2.782855   76  12.101505  6.246535
...             ...        ...  ...       ...  ...        ...       ...
2018-01-04      NaN  11.177106  NaN  2.782855   76  12.101505  6.246535
2018-01-05      NaN  11.177106  NaN  2.782855   76  12.101505  6.246535

AdminStrata
Indicator    Waterways
Datetime
2018-01-01   13.079334
2018-01-02   13.079334
...                ...
2018-01-04   13.079334
2018-01-05   13.079334

[5 rows x 218 columns]

In [8]:
PROVINCES = df.columns.get_level_values(0).unique()
PROVINCES

Index(['Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue',
       'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu',
       'Federal Capital Territory', 'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano',
       'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa', 'Niger',
       'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba',
       'Yobe', 'Zamfara'],
      dtype='object', name='AdminStrata')

In [9]:
PREDICTORS = df.columns.get_level_values(1).unique()
PREDICTORS

Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways',
       '1 Month Anomaly Rainfalls (%)', '3 Months Anomaly Rainfalls (%)',
       'FCG', 'Fatalities', 'NDVI', 'NDVI Anomaly', 'Population',
       'Price cereals and tubers', 'Rainfalls (mm)', 'Ramadan', 'rCSI'],
      dtype='object', name='Indicator')

In [10]:
for PROVINCE in PROVINCES:
    print(PROVINCE)
    print(df[PROVINCE].columns)

Abia
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Adamawa
Index(['1 Month Anomaly Rainfalls (%)', '3 Months Anomaly Rainfalls (%)',
       'Area', 'Code', 'FCG', 'Fatalities', 'Lat', 'Lon', 'NDVI',
       'NDVI Anomaly', 'Population', 'Price cereals and tubers',
       'Rainfalls (mm)', 'Ramadan', 'Waterways', 'rCSI'],
      dtype='object', name='Indicator')
Akwa Ibom
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Anambra
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Bauchi
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Bayelsa
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Benue
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Borno
Index(['1 Month Anomaly Rainfalls (%)', '3 Months Anomaly Rainfalls (%)',
       'Area', 'Code', 'FCG', 'Fatalities', 'Lat', 'Lon', 'NDVI',
       'NDVI Anomaly', 'Population', 'Price cereals and tubers',
       'Rainfalls (mm)', 'Ramadan', 'Waterways', 'rCSI'],
      dtype='object', name='Indicator')
Cross River
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Delta
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Ebonyi
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Edo
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Ekiti
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Enugu
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Federal Capital Territory
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Gombe
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Imo
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Jigawa
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Kaduna
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Kano
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Katsina
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Kebbi
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Kogi
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Kwara
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Lagos
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Nasarawa
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Niger
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Ogun
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Ondo
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Osun
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Oyo
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Plateau
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Rivers
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Sokoto
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Taraba
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')
Yobe
Index(['1 Month Anomaly Rainfalls (%)', '3 Months Anomaly Rainfalls (%)',
       'Area', 'Code', 'FCG', 'Fatalities', 'Lat', 'Lon', 'NDVI',
       'NDVI Anomaly', 'Population', 'Price cereals and tubers',
       'Rainfalls (mm)', 'Ramadan', 'Waterways', 'rCSI'],
      dtype='object', name='Indicator')
Zamfara
Index(['Area', 'Code', 'Lat', 'Lon', 'Waterways'], dtype='object', name='Indicator')

In [11]:
df = df.loc[:, df.columns.get_level_values(0).isin(["Adamawa", "Borno", "Yobe"])]

In [12]:
# Plot time-series.
TsIP(df).interactive_plot_df(title = "Time-series", matplotlib = False, style = "mix", comparison = False, first_last_valid_index_group = True)

interactive(children=(ToggleButtons(description='AdminStrata', options=('Adamawa', 'Borno', 'Yobe'), value='Ad…

In [13]:
# Save the datasets.
df.to_csv(PATH_TO_SAVE + f"{COUNTRY}.csv", index_label = False)