In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Add the python path to the folder containing some custom packages.
import sys
sys.path.insert(0, "../packages/")
from TsIP.TsIP import TsIP

In [3]:
# Set default sizes for figures.
plt.style.use("default") # style matplotlib
plt.rc("axes", labelsize = 12) # fontsize of the x and y labels
plt.rc("axes", titlesize = 15) # fontsize of the axes title
plt.rc("xtick", labelsize = 12) # fontsize of the tick labels
plt.rc("ytick", labelsize = 12) # fontsize of the tick labels
plt.rc("legend", fontsize = 12) # legend fontsize

In [4]:
dir_results = "./Yemen/output_test"

# Forecasting

In [5]:
# Load forecasting results.
xls = pd.ExcelFile(dir_results + "/forecast.xlsx")

forecast_splits = dict()
for i,split in enumerate(xls.sheet_names):
    if i == 0:
        df = pd.read_excel(xls, split, index_col = 0, header = [0, 1, 2])
    else:
        forecast_split = pd.read_excel(xls, split, index_col = 0, header = [0, 1, 2])
        forecast_split.drop("FCG", axis = 1, level = 2, inplace = True)
        forecast_split = pd.concat([df, forecast_split], axis = 1).sort_index(axis = 1, level = [0, 1, 2])
        # Save the predictions.
        forecast_splits[split] = forecast_split
    
forecast_splits = pd.concat(forecast_splits, axis = 1)
forecast_splits.columns.names = ["Split", "Country", "AdminStrata", "Prediction"]
forecast_splits.head()

Split        Split 1                                                           \
Country        Yemen
AdminStrata    Abyan                    Aden                Al Bayda
Prediction       FCG Forecast Naive      FCG Forecast Naive      FCG Forecast
Datetime
2018-07-02   31.1587      NaN   NaN  16.6195      NaN   NaN  38.3327      NaN
2018-07-03   32.6752      NaN   NaN  16.3706      NaN   NaN  43.2921      NaN
2018-07-04   33.4156      NaN   NaN  15.0892      NaN   NaN  45.1282      NaN
2018-07-05   33.5315      NaN   NaN  15.7665      NaN   NaN  43.9593      NaN
2018-07-06   33.9519      NaN   NaN  16.8701      NaN   NaN  44.5165      NaN

Split                         ... Split 10                                   \
Country                       ...    Yemen
AdminStrata       Al Dhale'e  ...   Sa'ada   Sana'a                 Shabwah
Prediction  Naive        FCG  ...    Naive      FCG Forecast Naive      FCG
Datetime                      ...
2018-07-02    NaN    29.1948  ...      NaN  26.9177      NaN   NaN  16.7523
2018-07-03    NaN    31.3369  ...      NaN  25.7835      NaN   NaN  18.2575
2018-07-04    NaN    33.1352  ...      NaN  25.4360      NaN   NaN  19.0831
2018-07-05    NaN    34.5543  ...      NaN  27.4218      NaN   NaN  20.3495
2018-07-06    NaN    33.8786  ...      NaN  26.5472      NaN   NaN  21.1075

Split
Country
AdminStrata                   Taizz
Prediction  Forecast Naive      FCG Forecast Naive
Datetime
2018-07-02       NaN   NaN  26.5634      NaN   NaN
2018-07-03       NaN   NaN  29.1240      NaN   NaN
2018-07-04       NaN   NaN  29.4280      NaN   NaN
2018-07-05       NaN   NaN  30.4560      NaN   NaN
2018-07-06       NaN   NaN  31.0125      NaN   NaN

[5 rows x 600 columns]

In [6]:
TsIP(forecast_splits).interactive_plot_df(title = "Time-series", matplotlib = False, style = "lines", comparison = False)

HBox(children=(Dropdown(description='Split', options=('Split 1', 'Split 2', 'Split 3', 'Split 4', 'Split 5', 'â€¦

RadioButtons(description='Select:', options=('Time-series', 'Missing values'), value='Time-series')

Output()